login/urls.py
from django.contrib import admin
from django.urls import path
from .views import CustomPasswordResetConfirmView, DepartureUser, LoginFormView, LogoutFormView, CustomPasswordResetView ,UserListView, UserUpdateView, activate_superuser, activate_user, create_superuser, deactivate_user, resend_mail, recive_mail
from . import views 
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    
    path('', LoginFormView.as_view(), name='login'),
    path('register/', views.register , name='register'),
    path('<str:schema_name>/create-superuser/', create_superuser, name='create-superuser'),
    path('recive-mail/', recive_mail, name='recive-mail'),
    path('resend-mail/', resend_mail, name='resend-mail'),
    path('activate/<uidb64>/<token>/', activate_superuser, name='activate-superuser'),
    path('logout/', LogoutFormView.as_view(), name='logout'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('reset-password/', PasswordResetView.as_view(template_name = 'password_reset.html'), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='reset_password_done.html'), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('users/', UserListView.as_view(), name='userlist' ),
    path('update-user/<int:pk>', UserUpdateView.as_view(), name='updateuser' ),
    path('deactivate-user/<int:pk>', DepartureUser.as_view(), name='deactivateuser' ),
    path('activate-user/<int:pk>', activate_user, name='activateuser' ),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db import transaction
from client.models import Client


class CustomUser(AbstractUser):
    avatar = models.ImageField(blank=True, null=True, upload_to='static/')
    position = models.CharField(max_length=80,null=True, verbose_name='Puesto')
    email = models.EmailField(unique=True)
    documento = models.CharField(max_length=8, blank=True, null=True, verbose_name='documento')
    birth_date = models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')
    address = models.CharField(max_length=100, blank=True, null=True, verbose_name='Domicilio')
    tel_number=models.CharField(max_length=13, blank=True, null=True, verbose_name='Nro Telefono')
    admission_date = models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso')
    departure_date = models.DateField(blank=True, null=True, verbose_name='Fecha Egreso')
    departure_motive = models.CharField(max_length=1000,blank=True, null=True, verbose_name='Motivo de baja')
    menu_color = models.CharField(max_length=7, null=True, blank=True, verbose_name='Color de menu', default='#212629')
    assigned_role = models.ForeignKey('permission.PermissionRoles', on_delete=models.CASCADE, verbose_name='Rol asignado', default=1)
    client = models.ForeignKey('client.Client', on_delete=models.CASCADE, null=True, blank=True)


    def formatted_birth_date(self):
        return self.birth_date.strftime('%Y-%m-%d') if self.birth_date else ''
    
    def formatted_admission_date(self):
        return self.admission_date.strftime('%Y-%m-%d') if self.admission_date else ''
    
    def formatted_departure_date(self):
        return self.departure_date.strftime('%Y-%m-%d') if self.departure_date else ''
    

    def inactivate(self):
        try:
            with transaction.atomic():
                self.is_active = False
                self.save(update_fields=['is_active'])
            message = f'Se inactivó el usuario <strong>{self.username}</strong> con éxito. Estado: {self.is_active}'
        except Exception as e:
            message = f'No se pudo inactivar el usuario <strong>{self.username}</strong>. Error: {str(e)}'
        return message
    
    
    def activate(self):
        try:
            self.is_active = True
            self.save()
            message = f'Se activó el usuario <strong>{self.username}</strong> con éxito.'
        except Exception as e:
            message = f'No se pudo activar el usuario <strong>{self.username}</strong>. Error: {str(e)}'
        return message
     

passbase/models.py
import hashlib
from django.utils import timezone
from datetime import datetime
from django.db import models
from django.forms import model_to_dict
from django.db.models.signals import post_save, pre_save
import re
from cryptography.fernet import Fernet

from login.models import CustomUser
from passbase.crypto import decrypt_data, encrypt_data
from passing import settings

# Create your models here.
class SeccionContra(models.Model):

    nombre_seccion = models.CharField(max_length=50)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = "Seccion"
        verbose_name_plural= "Secciones"
        
    def __str__(self):
        return self.nombre_seccion
    

class Contrasena(models.Model):
  

    nombre_contra = models.CharField(max_length=255, unique=True)
    seccion = models.ForeignKey(SeccionContra, on_delete=models.CASCADE)
    link = models.CharField(max_length=265)
    usuario = models.CharField(max_length=255)
    contraseña = models.CharField(max_length=500)
    actualizacion= models.PositiveSmallIntegerField(default=30) #la contraseña pedirá cambio cada x dias de este campo
    info = models.CharField(max_length=260)
    file = models.FileField(blank=True, null=True, upload_to='contra_files/')
    is_personal = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True)
    hash = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        verbose_name = "Contraseña"
        verbose_name_plural= "Contraseñas"
        
    def __str__(self):
        return str(self.id)
    
    def toJSON(self):
        item = model_to_dict(self)
        return item
    
    def save(self, *args, **kwargs):
        
        if isinstance(self.contraseña, str):
            self.contraseña = encrypt_data(self.contraseña)
        if isinstance(self.usuario, str):
            self.usuario = encrypt_data(self.usuario)
        super().save(*args, **kwargs)

    def get_decrypted_password(self):
        if not isinstance(self.contraseña, (bytes, str)):
            raise TypeError(f"Expected bytes or str, but got {type(self.contraseña).__name__}")
        return decrypt_data(self.contraseña)
    
    def get_decrypted_user(self):
        if not isinstance(self.usuario, (bytes, str)):
            raise TypeError(f"Expected bytes or str, but got {type(self.usuario).__name__}")
        return decrypt_data(self.usuario)
   
    def encrypt_password(self):
        if not isinstance(self.contraseña, (str)):
            raise TypeError(f"Expected bytes or str, but got {type(self.contraseña).__name__}")
        return encrypt_data(self.contraseña)
    
    def encrypt_user(self):
        if not isinstance(self.usuario, (str)):
            raise TypeError(f"Expected bytes or str, but got {type(self.usuario).__name__}")
        return encrypt_data(self.usuario)

    def ratio_calculation(self, created_value):
        fecha_hoy = timezone.now()
        dias_actualizacion = self.actualizacion
        dias_transcurridos = (fecha_hoy - created_value).days
        dias_faltantes = dias_actualizacion - dias_transcurridos
        
        try:
            ratio = dias_faltantes / dias_actualizacion
        except ZeroDivisionError:
            ratio = 0
        
        if ratio <= 0:
            return '#FF7367' #Contraseña Vencida
        elif 0.01 < ratio <= 0.09:
            return '#FFE682' #Contraseña por vencer
        else:
            return '#7CFF6D' #Contraseña en plazo

    def last_pass_change(self):
        log_data_change_pass = LogData.objects.filter(contraseña=self.id, action='change pass').order_by('-created')[:1]
        
        if log_data_change_pass.exists():
            log_data_objeto = log_data_change_pass.first()
            created_value = log_data_objeto.created
            return created_value
        else:
            log_data_created = LogData.objects.filter(contraseña=self.id, action='Create').order_by('-created')[:1]
            
            if log_data_created.exists():
                log_data_objeto = log_data_created.first()
                created_value = log_data_objeto.created
                return created_value
            else:
                return None

    @property
    def flag(self):
        created_value = self.last_pass_change()
        if created_value is None:
            return 'Sin data'
        return self.ratio_calculation(created_value)

    @property
    def last_change(self):
        created_value = self.last_pass_change()
        if created_value is None:
            return 'Sin data'
        if isinstance(created_value, str):
            created_value = datetime.fromisoformat(created_value)
        fecha_hoy = timezone.now()
        dias_transcurridos = (fecha_hoy - created_value).days
        return dias_transcurridos
    
    @property
    def password_strength(self):
        password = decrypt_data(self.contraseña)
        length = len(password)

        # Check for presence of different character types
        has_upper = re.search(r'[A-Z]', password) is not None
        has_lower = re.search(r'[a-z]', password) is not None
        has_digit = re.search(r'\d', password) is not None
        has_special = re.search(r'[!@#$%^&*(),.?":{}|<>]', password) is not None

        # Evaluate strength based on the criteria
        strength = 0

        if length >= 8:
            strength += 1
        if length >= 12:
            strength += 1
        if has_upper:
            strength += 1
        if has_lower:
            strength += 1
        if has_digit:
            strength += 1
        if has_special:
            strength += 1

        if strength <= 2:
            return 'weak'
        elif 3 <= strength <= 4:
            return 'moderate'
        elif strength >= 5:
            return 'strong'
    



        
class LogData(models.Model):
    entidad = models.CharField(max_length=50)
    contraseña = models.IntegerField()
    password = models.CharField(max_length=500, blank=True)
    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default='')
    action = models.CharField(max_length=80, blank=True)
    detail = models.CharField(max_length=2000)
    created = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = "Log"
        
    def __str__(self):
        return str(self.contraseña)
    
    def encrypt_password(self):
        if not isinstance(self.password, (str)):
            raise TypeError(f"Expected bytes or str, but got {type(self.password).__name__}")
        return encrypt_data(self.password)
    
    def get_decrypted_password(self):
        if not isinstance(self.password, (bytes, str)):
            raise TypeError(f"Expected bytes or str, but got {type(self.password).__name__}")
        return decrypt_data(self.password)
    
    def get_encrypted_user(self):
        try:
            usuario_encrypted_match = re.search(r'Usuario: (.+?),', self.detail)
            if usuario_encrypted_match:
                usuario_encrypted = usuario_encrypted_match.group(1).strip()
                
            else:
                usuario_encrypted = None
            return usuario_encrypted
        except Exception as e:
            print(f"Error extracting encrypted user: {e}")
            return None

    def get_decrypted_user(self, usuario_encrypted):
            if usuario_encrypted is None:
                return None
            else:
                return decrypt_data(usuario_encrypted)

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from .models import CustomUser
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3




class CustomLoginForm(AuthenticationForm):
    captcha = ReCaptchaField(
    widget=ReCaptchaV3(
        attrs={
            'required_score':0.8, #aumenta el score de puntuacion para la deteccion de bots
            
        }
    )
)
    
class SuperUserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label = 'Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label = 'Confirmar Contraseña', widget=forms.PasswordInput)
    captcha = ReCaptchaField(
    widget=ReCaptchaV3(
        attrs={
            'required_score':0.8, #aumenta el score de puntuacion para la deteccion de bots
            }
        )
    )

    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        help_texts = {k:"" for k in fields}
    
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Las contraseñas no coinciden')
        return cd['password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            form.field.widget.attrs['class']= 'form-control'
            form.field.widget.attrs['autocomplete']= 'off'




class ProfileForm(forms.ModelForm):
    menu_color = forms.CharField(
        max_length=7,  # El valor hexadecimal del color es de 7 caracteres (#XXXXXX)
        widget=forms.TextInput(attrs={'type': 'color'})
    )

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'avatar', 'position', 'menu_color']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)



class UserForm(forms.ModelForm):
    admission_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control' }),required=False)
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control' }),required=False)
    is_superuser = forms.RadioSelect()
    is_staff = forms.RadioSelect()
    is_active = forms.RadioSelect()
    documento = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    position = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    tel_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'documento', 'birth_date','address', 'tel_number','is_superuser', 'is_staff',  'is_active' ,'position', 'admission_date','assigned_role']
        

class UserDepartureForm(forms.ModelForm):
     departure_date = forms.DateField(label= 'Fecha de baja',widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}))
     departure_motive = forms.CharField(label= 'Motivo de baja',widget=forms.Textarea(attrs={'class': 'form-control'}))
     class Meta:
        model = CustomUser
        fields = ['departure_date', 'departure_motive', 'is_active']

        

   


class AdminLoginForm(AuthenticationForm):
    captcha = ReCaptchaField(
    widget=ReCaptchaV3(
        attrs={
            'required_score':0.8, #aumenta el score de puntuacion para la deteccion de bots
            
        }
    )
)

templates/activation_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Hola {{ user.name }}, {{user.last_name}},</p>
    <p>Gracias por registrarte. Por favor, haz clic en el enlace a continuación para activar tu cuenta de superusuario:</p>
    <p><a href="{{ activation_url }}">Activar mi cuenta</a></p>
    <p>Si no solicitaste esta cuenta, por favor ignora este correo.</p>
</body>
</html>

templates/client_register.html
{% extends 'base.html'%}


{% block content %}
<div class ='justify-content-sm-center'>
<div class="d-flex justify-content-center" >

    <div class="card center">
            <div class="card-title">
                <div class="container" style="height: 105px; padding-top: 20px;">
                    <h2><i class="fas fa-address-card" ></i> {{title}}</h2>
                    
                </div>
            </div>

            <div class="card-body "style="background-color: #F7F7F7; width: 26rem;">


                    <form class = 'form' method="POST">
                        {% csrf_token %}
                        
                        {{form.as_p}}
                        
                        <button type="submit" class="btn btn-primary btn-flat">
                            <i class="fas fa-address-card"></i> Registrarse
                        </button>
                            
                     
                        
                        </div> 
                    </form>
            </div>
            
        </div>
    </div>
</div>
{% endblock %}

templates/create-cont.html
{% extends 'base.html'%}


{% block content %}
<body>
<div class="container pt-5" >
    <div class="row">
        <div class="col-md-5 mx-auto"> 
    
            <div class="card-title" >
                <div class="container" style="height: 105px; padding-top: 20px;"style="background-color: #F7F7F7 ;">
                    <h2><i class="fas fa-plus" ></i>{{title}}</h2>
                    <button class="btn">
                        <a class="btn btn-primary btn-flat" href= {% url 'listpass' %}> <i class="fa-solid fa-bars"></i>  Lista</a>
                    </button>
                </div>
            </div>

            <div class="card-body">
                    <form method="POST" action="{% url 'createpass' %}" enctype="multipart/form-data">
                        {% csrf_token %}

                        {{form.errors}}
                        

                        <div class="form-group">

                            <label for="nombre_contra" style="margin-top:20px;">Nombre de Contraseña: </label>
                            <input id="nombre_contra" type="text" class='form-control' name="nombre_contra" maxlength="100" style="margin-top:5px;" required>
                            

                            <label for="seccion" style="margin-top:20px;">Sección:</label>

                            <div class="input-group">
                            
                                <select name="seccion" placeholder="Elija la seccion" class="form-control" autocomplete="off" style="margin-top:5px;" required="" id="id_seccion">
                                  {% for section in sections %}
                                  <option value = {{section.id}}> {{section.nombre_seccion}} </option>
                                  {% endfor %}
                                     
                                </select>
                                <a class="btn btn-primary center" href="{% url 'createsection' %}"><i class="fas fa-plus" style="margin-top:5px;"></i></a> 

                            </div>

                            <label for="link" style="margin-top:20px;">Link: </label>
                            <input id="link" type="text" class='form-control' name="link" maxlength="100" style="margin-top:5px;" required>

                            <label for="usuario" style="margin-top:20px;">Usuario: </label>
                            <input id="usuario" type="text" class='form-control' name="usuario" maxlength="100" style="margin-top:5px;" required>

                           <!-- Aqui está el generador de contraseñas -->
                            <div class="card text-bg-light" style="margin-top:10px;">

                                <div class="card-header" style="display:flex; justify-content: space-between;">Genera una Contraseña
                                    <button type="button" class="btn btn-flat" id="toggleParamsBtn" title="Opciones" ><i class="fa-solid fa-circle-chevron-down" style="color:rgb(11, 094, 215)"></i></button>
                                </div>

                                <div class="card-body">

                                    
                                        <div id="parametrosInputs" style="display:none; justify-content: flex;">
                                            
                                            <label for="longitud">Longitud:</label>
                                            <input class="form-control" type="number" id="longitud" name="longitud" value="12" min="6" max="32"><br>
                                            <label><input class="form-check-input" type="checkbox" id="incluirMayusculas" name="incluirMayusculas" checked> Incluir mayúsculas</label><br>
                                            <label><input class="form-check-input" type="checkbox" id="incluirMinusculas" name="incluirMinusculas" checked> Incluir minúsculas</label><br>
                                            <label><input class="form-check-input" type="checkbox" id="incluirNumeros" name="incluirNumeros" checked> Incluir números</label><br>
                                            <label><input class="form-check-input" type="checkbox" id="incluirSimbolos" name="incluirSimbolos"> Incluir símbolos</label><br>
                                            <button type="button" class="btn btn-primary btn-flat" style="margin-top:10px;" title="Generar contraseña" id="generarContrasenaBtn">Generar
                                                <i class="fa-solid fa-wand-magic-sparkles"></i>
                                            </button>
                                        </div>
                                        
                                    
                                    
                                </div>
                            </div>
                            <!-- Aqui termina el generador de contraseñas -->
                            <div class= 'input group'>
                                <label for="contraseña" style="margin-top:7px;">Contraseña: </label>
                                

                                <div class="input-group mb-3">
                                    <input id="contraseña" type="password" class='form-control' name="contraseña" maxlength="100" required>
                                    <button class="btn btn-outline-primary" type="button" id="passwordToggle">
                                        <i class="fas fa-eye toggle-password-icon" id="eyeIcon"></i>
                                    </button>
                                </div>
                            </div>

                            <label for="actualizacion" style="margin-top:20px;">Actualizacion: </label>
                            <input id="actualizacion" type="number" pattern="[0-9]+" class='form-control' title="Ingrese solo números positivos" name="actualizacion" maxlength="100" style="margin-top:5px;" required>

                            <div class="form-group">
                                <label for="info" style="margin-top: 20px;">Info</label>
                                <input id="info" type="text" class="form-control" name="info" maxlength="100" style="margin-top: 5px;" required>
                            </div>
                            <div class="form-check form-check-inline" style="margin-top: 20px;">
                                <label class="form-check-label" for="is_personal">
                                    Contraseña Personal
                                </label>
                                <input class="form-check-input" type="checkbox" title="Marca esta casilla si esta cintraseña es solo de uso personal y no necesitas compartirla con nadie" id="is_personal" name="is_personal">
                                <i class="fa-solid fa-circle-question" style="color:rgb(79, 64, 247)" title="Marca esta casilla si esta contraseña es solo de uso personal y no necesitas compartirla con nadie"></i>
                                
                            </div>

                            <div class="form-group" style="margin-top: 20px;">
                                <label for="file">Archivo</label>
                                <input id="file" type="file" class="form-control-file" name="file">
                            </div>

                        </div>
                            
                            <button type="submit" class="btn btn-primary btn-flat" style="margin-top:20px;">
                                <i class="fas fa-save"></i> Guardar registro
                            </button>

                        </div> 
                    </form>
            </div>
            </div>
        </div>
    </div>




        
        
</div>
</body>

<script>
    document.getElementById('toggleParamsBtn').addEventListener('click', function() {
        event.preventDefault(); // Prevenir el envío del formulario interno
        var parametrosInputs = document.getElementById('parametrosInputs');
        parametrosInputs.style.display = parametrosInputs.style.display === 'none' ? 'block' : 'none';
    });
    
    document.getElementById('generarContrasenaBtn').addEventListener('click', function() {
        // Obtener los valores de los parámetros
        const longitud = document.getElementById('longitud').value;
        const incluirMayusculas = document.getElementById('incluirMayusculas').checked;
        const incluirMinusculas = document.getElementById('incluirMinusculas').checked;
        const incluirNumeros = document.getElementById('incluirNumeros').checked;
        const incluirSimbolos = document.getElementById('incluirSimbolos').checked;
    
        // Generar la contraseña en el frontend
        var caracteresPermitidos = '';
        if (incluirMayusculas) caracteresPermitidos += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        if (incluirMinusculas) caracteresPermitidos += 'abcdefghijklmnopqrstuvwxyz';
        if (incluirNumeros) caracteresPermitidos += '0123456789';
        if (incluirSimbolos) caracteresPermitidos += '!@#$%^&_+=|:"<>?/~';
    
        var contrasenaGenerada = '';
        for (var i = 0; i < longitud; i++) {
            var randomIndex = Math.floor(Math.random() * caracteresPermitidos.length);
            contrasenaGenerada += caracteresPermitidos.charAt(randomIndex);
        }
    
        // Mostrar la contraseña generada
        document.getElementById('contraseña').setAttribute('value', contrasenaGenerada);

        // Copiar la contraseña al portapapeles
        navigator.clipboard.writeText(contrasenaGenerada)
        .then(() => {
            console.log('Contraseña copiada al portapapeles.');
            mostrarMensajeTemporal('Contraseña copiada', 2000);
        })
        .catch(err => {
            console.error('Error al copiar la contraseña al portapapeles:', err);
        });
    });
    function mostrarMensajeTemporal(mensaje, duracion) {
        var mensajeDiv = document.createElement('div');
        mensajeDiv.textContent = mensaje;
        mensajeDiv.style.position = 'fixed';
        mensajeDiv.style.top = '10px';
        mensajeDiv.style.left = '50%';
        mensajeDiv.style.transform = 'translateX(-50%)';
        mensajeDiv.style.backgroundColor = 'rgba(0, 0, 0, 0.8)';
        mensajeDiv.style.color = 'white';
        mensajeDiv.style.padding = '10px';
        mensajeDiv.style.borderRadius = '5px';
        mensajeDiv.style.zIndex = '9999';
        document.body.appendChild(mensajeDiv);

        setTimeout(function() {
            mensajeDiv.parentNode.removeChild(mensajeDiv);
        }, duracion);
    }
</script>
<script>
    const inputPassword = document.getElementById("contraseña");
    const iconEye = document.getElementById("eyeIcon");

    iconEye.addEventListener('click', function() {
        if (inputPassword.type === 'password') {
            inputPassword.type = 'text';
            iconEye.classList.remove('fa-eye');
            iconEye.classList.add('fa-eye-slash');
        } else {
            inputPassword.type = 'password';
            iconEye.classList.remove('fa-eye-slash');
            iconEye.classList.add('fa-eye');
        }
    });
</script>
{% endblock %}

templates/delete-cont.html
{% extends 'base.html'%}


{% block content %}

<div class="container pt-5" >

    <div class="card center">
            <div class="card-title">
                <div class="container" style="height: 85px; padding-top: 20px;">
                    <h2><i class="fas fa-trash" ></i> {{title}}</h2>
                    
                </div>
            </div>

            <div class="card-body"style="background-color: #F7F7F7 ;">
                <div class="card-body">
                    <form method="POST" >
                        {% csrf_token %}
                    <h5> ¿Estas Seguro que deseas borrar esta contraseña de {{ object.nombre_contra }}? </h5>

                </div>
                                     
                <button type="submit" class="btn btn-danger">           
                    <i class="fas fa-trash" class="btn btn-danger"></i> Eliminar
                </button>        
                            
                            <button  class="btn">
                                <a class="btn btn-primary btn-flat" href= {% url 'listpass' %}> <i class="fas fa-ban"></i> Cancelar </a>
                            </button>
                        </div> 
                    </form>
            </div>
            
        </div>
    </div>

    {% endblock %}

        
</div>